---
- hosts: all
  tasks:
  - name: install base packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - vim
      - screen
      - tmux
      - bc
      - build-essential
      - bzip2
      - ca-certificates
      - cifs-utils
      - cpp
      - cups-bsd
      - cups-client
      - cups-common
      - curl
      - dash
      - diffutils
      - dmsetup
      - dosfstools
      - dpkg-dev
      - e2fsprogs
      - ed
      - findutils
      - fuse
      - g++
      - gcc
      - gconf-service
      - gconf2
      - gconf2-common
      - gdb
      - gdbserver
      - gettext-base
      - ghostscript
      - git
      - git-core
      - git-man
      - gnupg
      - gpgv
      - gpicview
      - grep
      - groff-base
      - gzip
      - i2c-tools
      - idle
      - idle3
      - initramfs-tools
      - initscripts
      - iproute
      - iptables
      - iputils-ping
      - java-common
      - klibc-utils
      - kmod
      - krb5-locales
      - less
      - lightdm
      - lightdm-gtk-greeter
      - linux-libc-dev
      - locales
      - login
      - logrotate
      - lsb-base
      - lua5.1
      - luajit
      - lxappearance
      - lxde
      - lxde-common
      - lxde-core
      - lxde-icon-theme
      - lxinput
      - lxmenu-data
      - lxpanel
      - lxpolkit
      - lxrandr
      - lxsession
      - lxsession-edit
      - lxshortcut
      - lxtask
      - lxterminal
      - make
      - makedev
      - man-db
      - manpages
      - manpages-dev
      - mawk
      - menu
      - menu-xdg
      - mime-support
      - minecraft-pi
      - mount
      - mountall
      - multiarch-support
      - nano
      - ncdu
      - ncurses-base
      - ncurses-bin
      - ncurses-term
      - net-tools
      - netbase
      - netcat-openbsd
      - netcat-traditional
      - netsurf-common
      - netsurf-gtk
      - nfs-common
      - ntp
      - obconf
      - omxplayer
      - openbox
      - openssh-blacklist
      - openssh-blacklist-extra
      - openssh-client
      - openssh-server
      - openssl
      - oracle-java8-jdk
      - parted
      - patch
      - pciutils
      - pcmanfm

      - perl
      - perl-base
      - perl-modules

      - pkg-config
      - plymouth
      - policykit-1
      - poppler-data
      - poppler-utils
      - procps
      - psmisc
      - pypy-setuptools



      - python
      - python-dbus
      - python-dbus-dev
      - python-dev
      - python-gi
      - python-minecraftpi
      - python-minimal
      - python-numpy
      - python-picamera


      - python-pip
      - python-pkg-resources
      - python-pycurl
      - python-pygame
      - python-pywapi
      - python-rpi.gpio
      - python-serial
      - python-setuptools
      - python-smbus
      - python-support
      - python-tk
      - python3
      - python3-dev
      - python3-minimal
      - python3-numpy
      - python3-picamera



      - python3-pip
      - python3-pkg-resources
      - python3-rpi.gpio
      - python3-serial
      - python3-setuptools
      - python3-tk


      - qdbus
      - qjackctl
      - raspberrypi-artwork
      - raspberrypi-bootloader
      - raspbian-archive-keyring
      - raspi-config
      - raspi-copies-and-fills
      - readline-common
      - rpcbind
      - rpi-update
      - rsync
      - rsyslog
      - ruby
      - samba-common
      - scratch
      - screen
      - sed
      - sensible-utils
      - sgml-base
      - shared-mime-info
      - smartsim
      - smbclient
      - sonic-pi
      - squeak-plugins-scratch
      - squeak-vm
      - ssh
      - strace
      - sudo
      - supercollider
      - supercollider-common
      - supercollider-server
      - sysstat
      - sysv-rc
      - sysvbanner
      - tar
      - tasksel
      - tasksel-data
      - tcl
      - tcpd
      - timidity
      - tk
      - traceroute
      - ttf-dejavu-core
      - ucf
      - udev
      - udisks
      - unzip
      - update-inetd
      - usbmuxd
      - usbutils
      - util-linux
      - v4l-utils
      - vim
      - vim-common
      - vim-runtime
      - vim-tiny
      - weather-util
      - weather-util-data
      - weston
      - wget
      - whiptail
      - wireless-tools
      - wpagui
      - wpasupplicant
      - zenity
      - zenity-common
      - zlib1g
      - zlib1g-dev
